// Generated by generate_emit_runner.mjs. DO NOT EDIT.
pub mod generated;
use std::fs;
use std::path::Path;

mod test_scalars;
mod test_all_types;

fn main() {
    let vec_dir = std::env::var("VEC_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::create_dir_all(&out_dir).unwrap();
    fs::create_dir_all(Path::new(&out_dir).join("scalars")).unwrap();

    let mut passed = 0u32;
    let mut failed = 0u32;

    let (p, f) = test_scalars::run(&vec_dir, &out_dir); passed += p; failed += f;
    let (p, f) = test_all_types::run(&vec_dir, &out_dir); passed += p; failed += f;

    println!("emit-rust: {} passed, {} failed", passed, failed);
    if failed > 0 {
        std::process::exit(1);
    }
}
