// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_many_types::*;


fn test_model_five01(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five01.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five01_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five01_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five01.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five01 mp: write error"); failed += 1; }
        } else { println!("FAIL Five01 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five01 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five01.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five01_decode(&mut r) {
                let mut w = JsonWriter::new();
                five01_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five01.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five01 json: write error"); failed += 1; }
            } else { println!("FAIL Five01 json: decode error"); failed += 1; }
        } else { println!("FAIL Five01 json: reader error"); failed += 1; }
    } else { println!("FAIL Five01 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five01.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five01_decode(&mut r) {
                let mut w = JsonWriter::new();
                five01_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five01.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five01 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five01 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five01 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five01 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five01.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five01_decode(&mut r) {
            let mut w = GronWriter::new();
            five01_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five01.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five01 gron: write error"); failed += 1; }
        } else { println!("FAIL Five01 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five01 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five02(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five02.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five02_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five02_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five02.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five02 mp: write error"); failed += 1; }
        } else { println!("FAIL Five02 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five02 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five02.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five02_decode(&mut r) {
                let mut w = JsonWriter::new();
                five02_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five02.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five02 json: write error"); failed += 1; }
            } else { println!("FAIL Five02 json: decode error"); failed += 1; }
        } else { println!("FAIL Five02 json: reader error"); failed += 1; }
    } else { println!("FAIL Five02 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five02.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five02_decode(&mut r) {
                let mut w = JsonWriter::new();
                five02_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five02.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five02 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five02 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five02 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five02 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five02.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five02_decode(&mut r) {
            let mut w = GronWriter::new();
            five02_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five02.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five02 gron: write error"); failed += 1; }
        } else { println!("FAIL Five02 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five02 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five03(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five03.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five03_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five03_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five03.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five03 mp: write error"); failed += 1; }
        } else { println!("FAIL Five03 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five03 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five03.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five03_decode(&mut r) {
                let mut w = JsonWriter::new();
                five03_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five03.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five03 json: write error"); failed += 1; }
            } else { println!("FAIL Five03 json: decode error"); failed += 1; }
        } else { println!("FAIL Five03 json: reader error"); failed += 1; }
    } else { println!("FAIL Five03 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five03.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five03_decode(&mut r) {
                let mut w = JsonWriter::new();
                five03_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five03.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five03 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five03 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five03 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five03 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five03.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five03_decode(&mut r) {
            let mut w = GronWriter::new();
            five03_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five03.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five03 gron: write error"); failed += 1; }
        } else { println!("FAIL Five03 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five03 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five04(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five04.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five04_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five04_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five04.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five04 mp: write error"); failed += 1; }
        } else { println!("FAIL Five04 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five04 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five04.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five04_decode(&mut r) {
                let mut w = JsonWriter::new();
                five04_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five04.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five04 json: write error"); failed += 1; }
            } else { println!("FAIL Five04 json: decode error"); failed += 1; }
        } else { println!("FAIL Five04 json: reader error"); failed += 1; }
    } else { println!("FAIL Five04 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five04.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five04_decode(&mut r) {
                let mut w = JsonWriter::new();
                five04_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five04.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five04 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five04 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five04 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five04 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five04.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five04_decode(&mut r) {
            let mut w = GronWriter::new();
            five04_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five04.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five04 gron: write error"); failed += 1; }
        } else { println!("FAIL Five04 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five04 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five05(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five05.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five05_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five05_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five05.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five05 mp: write error"); failed += 1; }
        } else { println!("FAIL Five05 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five05 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five05.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five05_decode(&mut r) {
                let mut w = JsonWriter::new();
                five05_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five05.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five05 json: write error"); failed += 1; }
            } else { println!("FAIL Five05 json: decode error"); failed += 1; }
        } else { println!("FAIL Five05 json: reader error"); failed += 1; }
    } else { println!("FAIL Five05 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five05.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five05_decode(&mut r) {
                let mut w = JsonWriter::new();
                five05_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five05.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five05 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five05 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five05 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five05 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five05.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five05_decode(&mut r) {
            let mut w = GronWriter::new();
            five05_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five05.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five05 gron: write error"); failed += 1; }
        } else { println!("FAIL Five05 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five05 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five06(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five06.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five06_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five06_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five06.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five06 mp: write error"); failed += 1; }
        } else { println!("FAIL Five06 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five06 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five06.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five06_decode(&mut r) {
                let mut w = JsonWriter::new();
                five06_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five06.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five06 json: write error"); failed += 1; }
            } else { println!("FAIL Five06 json: decode error"); failed += 1; }
        } else { println!("FAIL Five06 json: reader error"); failed += 1; }
    } else { println!("FAIL Five06 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five06.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five06_decode(&mut r) {
                let mut w = JsonWriter::new();
                five06_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five06.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five06 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five06 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five06 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five06 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five06.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five06_decode(&mut r) {
            let mut w = GronWriter::new();
            five06_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five06.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five06 gron: write error"); failed += 1; }
        } else { println!("FAIL Five06 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five06 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five07(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five07.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five07_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five07_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five07.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five07 mp: write error"); failed += 1; }
        } else { println!("FAIL Five07 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five07 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five07.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five07_decode(&mut r) {
                let mut w = JsonWriter::new();
                five07_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five07.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five07 json: write error"); failed += 1; }
            } else { println!("FAIL Five07 json: decode error"); failed += 1; }
        } else { println!("FAIL Five07 json: reader error"); failed += 1; }
    } else { println!("FAIL Five07 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five07.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five07_decode(&mut r) {
                let mut w = JsonWriter::new();
                five07_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five07.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five07 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five07 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five07 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five07 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five07.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five07_decode(&mut r) {
            let mut w = GronWriter::new();
            five07_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five07.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five07 gron: write error"); failed += 1; }
        } else { println!("FAIL Five07 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five07 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five08(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five08.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five08_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five08_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five08.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five08 mp: write error"); failed += 1; }
        } else { println!("FAIL Five08 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five08 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five08.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five08_decode(&mut r) {
                let mut w = JsonWriter::new();
                five08_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five08.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five08 json: write error"); failed += 1; }
            } else { println!("FAIL Five08 json: decode error"); failed += 1; }
        } else { println!("FAIL Five08 json: reader error"); failed += 1; }
    } else { println!("FAIL Five08 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five08.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five08_decode(&mut r) {
                let mut w = JsonWriter::new();
                five08_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five08.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five08 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five08 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five08 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five08 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five08.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five08_decode(&mut r) {
            let mut w = GronWriter::new();
            five08_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five08.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five08 gron: write error"); failed += 1; }
        } else { println!("FAIL Five08 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five08 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five09(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five09.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five09_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five09_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five09.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five09 mp: write error"); failed += 1; }
        } else { println!("FAIL Five09 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five09 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five09.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five09_decode(&mut r) {
                let mut w = JsonWriter::new();
                five09_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five09.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five09 json: write error"); failed += 1; }
            } else { println!("FAIL Five09 json: decode error"); failed += 1; }
        } else { println!("FAIL Five09 json: reader error"); failed += 1; }
    } else { println!("FAIL Five09 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five09.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five09_decode(&mut r) {
                let mut w = JsonWriter::new();
                five09_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five09.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five09 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five09 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five09 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five09 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five09.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five09_decode(&mut r) {
            let mut w = GronWriter::new();
            five09_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five09.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five09 gron: write error"); failed += 1; }
        } else { println!("FAIL Five09 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five09 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_five10(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five10.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = five10_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            five10_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five10.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five10 mp: write error"); failed += 1; }
        } else { println!("FAIL Five10 mp: decode error"); failed += 1; }
    } else { println!("FAIL Five10 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five10.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five10_decode(&mut r) {
                let mut w = JsonWriter::new();
                five10_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five10.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five10 json: write error"); failed += 1; }
            } else { println!("FAIL Five10 json: decode error"); failed += 1; }
        } else { println!("FAIL Five10 json: reader error"); failed += 1; }
    } else { println!("FAIL Five10 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five10.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = five10_decode(&mut r) {
                let mut w = JsonWriter::new();
                five10_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Five10.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Five10 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Five10 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Five10 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Five10 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Five10.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = five10_decode(&mut r) {
            let mut w = GronWriter::new();
            five10_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Five10.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Five10 gron: write error"); failed += 1; }
        } else { println!("FAIL Five10 gron: decode error"); failed += 1; }
    } else { println!("FAIL Five10 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_ten01(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten01.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = ten01_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            ten01_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten01.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten01 mp: write error"); failed += 1; }
        } else { println!("FAIL Ten01 mp: decode error"); failed += 1; }
    } else { println!("FAIL Ten01 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten01.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten01_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten01_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten01.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten01 json: write error"); failed += 1; }
            } else { println!("FAIL Ten01 json: decode error"); failed += 1; }
        } else { println!("FAIL Ten01 json: reader error"); failed += 1; }
    } else { println!("FAIL Ten01 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten01.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten01_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten01_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten01.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten01 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Ten01 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Ten01 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Ten01 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten01.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = ten01_decode(&mut r) {
            let mut w = GronWriter::new();
            ten01_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten01.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten01 gron: write error"); failed += 1; }
        } else { println!("FAIL Ten01 gron: decode error"); failed += 1; }
    } else { println!("FAIL Ten01 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_ten02(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten02.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = ten02_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            ten02_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten02.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten02 mp: write error"); failed += 1; }
        } else { println!("FAIL Ten02 mp: decode error"); failed += 1; }
    } else { println!("FAIL Ten02 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten02.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten02_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten02_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten02.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten02 json: write error"); failed += 1; }
            } else { println!("FAIL Ten02 json: decode error"); failed += 1; }
        } else { println!("FAIL Ten02 json: reader error"); failed += 1; }
    } else { println!("FAIL Ten02 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten02.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten02_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten02_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten02.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten02 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Ten02 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Ten02 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Ten02 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten02.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = ten02_decode(&mut r) {
            let mut w = GronWriter::new();
            ten02_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten02.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten02 gron: write error"); failed += 1; }
        } else { println!("FAIL Ten02 gron: decode error"); failed += 1; }
    } else { println!("FAIL Ten02 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_ten03(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten03.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = ten03_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            ten03_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten03.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten03 mp: write error"); failed += 1; }
        } else { println!("FAIL Ten03 mp: decode error"); failed += 1; }
    } else { println!("FAIL Ten03 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten03.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten03_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten03_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten03.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten03 json: write error"); failed += 1; }
            } else { println!("FAIL Ten03 json: decode error"); failed += 1; }
        } else { println!("FAIL Ten03 json: reader error"); failed += 1; }
    } else { println!("FAIL Ten03 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten03.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten03_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten03_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten03.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten03 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Ten03 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Ten03 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Ten03 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten03.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = ten03_decode(&mut r) {
            let mut w = GronWriter::new();
            ten03_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten03.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten03 gron: write error"); failed += 1; }
        } else { println!("FAIL Ten03 gron: decode error"); failed += 1; }
    } else { println!("FAIL Ten03 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_ten04(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten04.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = ten04_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            ten04_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten04.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten04 mp: write error"); failed += 1; }
        } else { println!("FAIL Ten04 mp: decode error"); failed += 1; }
    } else { println!("FAIL Ten04 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten04.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten04_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten04_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten04.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten04 json: write error"); failed += 1; }
            } else { println!("FAIL Ten04 json: decode error"); failed += 1; }
        } else { println!("FAIL Ten04 json: reader error"); failed += 1; }
    } else { println!("FAIL Ten04 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten04.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten04_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten04_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten04.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten04 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Ten04 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Ten04 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Ten04 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten04.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = ten04_decode(&mut r) {
            let mut w = GronWriter::new();
            ten04_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten04.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten04 gron: write error"); failed += 1; }
        } else { println!("FAIL Ten04 gron: decode error"); failed += 1; }
    } else { println!("FAIL Ten04 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_ten05(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten05.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = ten05_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            ten05_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten05.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten05 mp: write error"); failed += 1; }
        } else { println!("FAIL Ten05 mp: decode error"); failed += 1; }
    } else { println!("FAIL Ten05 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten05.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten05_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten05_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten05.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten05 json: write error"); failed += 1; }
            } else { println!("FAIL Ten05 json: decode error"); failed += 1; }
        } else { println!("FAIL Ten05 json: reader error"); failed += 1; }
    } else { println!("FAIL Ten05 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten05.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = ten05_decode(&mut r) {
                let mut w = JsonWriter::new();
                ten05_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten05.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Ten05 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Ten05 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Ten05 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Ten05 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Ten05.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = ten05_decode(&mut r) {
            let mut w = GronWriter::new();
            ten05_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Ten05.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Ten05 gron: write error"); failed += 1; }
        } else { println!("FAIL Ten05 gron: decode error"); failed += 1; }
    } else { println!("FAIL Ten05 gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_five01(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five02(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five03(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five04(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five05(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five06(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five07(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five08(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five09(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_five10(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_ten01(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_ten02(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_ten03(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_ten04(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_ten05(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
