// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_arrays_types::*;


fn test_model_arr_string(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrString.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_string_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrString.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrString mp: write error"); failed += 1; }
        } else { println!("FAIL ArrString mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrString mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrString.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrString.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrString json: write error"); failed += 1; }
            } else { println!("FAIL ArrString json: decode error"); failed += 1; }
        } else { println!("FAIL ArrString json: reader error"); failed += 1; }
    } else { println!("FAIL ArrString json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrString.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrString.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrString unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrString unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrString unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrString unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrString.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_string_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrString.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrString gron: write error"); failed += 1; }
        } else { println!("FAIL ArrString gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrString gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_int32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_int32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrInt32 mp: write error"); failed += 1; }
        } else { println!("FAIL ArrInt32 mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrInt32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrInt32 json: write error"); failed += 1; }
            } else { println!("FAIL ArrInt32 json: decode error"); failed += 1; }
        } else { println!("FAIL ArrInt32 json: reader error"); failed += 1; }
    } else { println!("FAIL ArrInt32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrInt32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrInt32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrInt32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrInt32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_int32_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrInt32 gron: write error"); failed += 1; }
        } else { println!("FAIL ArrInt32 gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrInt32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_boolean(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBoolean.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_boolean_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBoolean.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrBoolean mp: write error"); failed += 1; }
        } else { println!("FAIL ArrBoolean mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrBoolean mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBoolean.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBoolean.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrBoolean json: write error"); failed += 1; }
            } else { println!("FAIL ArrBoolean json: decode error"); failed += 1; }
        } else { println!("FAIL ArrBoolean json: reader error"); failed += 1; }
    } else { println!("FAIL ArrBoolean json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBoolean.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBoolean.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrBoolean unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrBoolean unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrBoolean unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrBoolean unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBoolean.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_boolean_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBoolean.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrBoolean gron: write error"); failed += 1; }
        } else { println!("FAIL ArrBoolean gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrBoolean gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_float64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrFloat64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_float64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrFloat64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrFloat64 mp: write error"); failed += 1; }
        } else { println!("FAIL ArrFloat64 mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrFloat64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrFloat64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrFloat64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrFloat64 json: write error"); failed += 1; }
            } else { println!("FAIL ArrFloat64 json: decode error"); failed += 1; }
        } else { println!("FAIL ArrFloat64 json: reader error"); failed += 1; }
    } else { println!("FAIL ArrFloat64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrFloat64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrFloat64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrFloat64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrFloat64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrFloat64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrFloat64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrFloat64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_float64_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrFloat64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrFloat64 gron: write error"); failed += 1; }
        } else { println!("FAIL ArrFloat64 gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrFloat64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_bytes(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBytes.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_bytes_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBytes.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrBytes mp: write error"); failed += 1; }
        } else { println!("FAIL ArrBytes mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrBytes mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBytes.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBytes.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrBytes json: write error"); failed += 1; }
            } else { println!("FAIL ArrBytes json: decode error"); failed += 1; }
        } else { println!("FAIL ArrBytes json: reader error"); failed += 1; }
    } else { println!("FAIL ArrBytes json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBytes.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBytes.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrBytes unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrBytes unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrBytes unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrBytes unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrBytes.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_bytes_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrBytes.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrBytes gron: write error"); failed += 1; }
        } else { println!("FAIL ArrBytes gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrBytes gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_int64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_int64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrInt64 mp: write error"); failed += 1; }
        } else { println!("FAIL ArrInt64 mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrInt64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrInt64 json: write error"); failed += 1; }
            } else { println!("FAIL ArrInt64 json: decode error"); failed += 1; }
        } else { println!("FAIL ArrInt64 json: reader error"); failed += 1; }
    } else { println!("FAIL ArrInt64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrInt64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrInt64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrInt64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrInt64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrInt64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_int64_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrInt64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrInt64 gron: write error"); failed += 1; }
        } else { println!("FAIL ArrInt64 gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrInt64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_arr_uint64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrUint64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = arr_uint64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            arr_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrUint64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrUint64 mp: write error"); failed += 1; }
        } else { println!("FAIL ArrUint64 mp: decode error"); failed += 1; }
    } else { println!("FAIL ArrUint64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrUint64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrUint64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrUint64 json: write error"); failed += 1; }
            } else { println!("FAIL ArrUint64 json: decode error"); failed += 1; }
        } else { println!("FAIL ArrUint64 json: reader error"); failed += 1; }
    } else { println!("FAIL ArrUint64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrUint64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = arr_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                arr_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrUint64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ArrUint64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL ArrUint64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ArrUint64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ArrUint64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ArrUint64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = arr_uint64_decode(&mut r) {
            let mut w = GronWriter::new();
            arr_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ArrUint64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ArrUint64 gron: write error"); failed += 1; }
        } else { println!("FAIL ArrUint64 gron: decode error"); failed += 1; }
    } else { println!("FAIL ArrUint64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_multi_arr1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = multi_arr1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            multi_arr1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr1 mp: write error"); failed += 1; }
        } else { println!("FAIL MultiArr1 mp: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr1_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr1 json: write error"); failed += 1; }
            } else { println!("FAIL MultiArr1 json: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr1 json: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr1_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL MultiArr1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = multi_arr1_decode(&mut r) {
            let mut w = GronWriter::new();
            multi_arr1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr1 gron: write error"); failed += 1; }
        } else { println!("FAIL MultiArr1 gron: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_multi_arr2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = multi_arr2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            multi_arr2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr2 mp: write error"); failed += 1; }
        } else { println!("FAIL MultiArr2 mp: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr2_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr2 json: write error"); failed += 1; }
            } else { println!("FAIL MultiArr2 json: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr2 json: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr2_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL MultiArr2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = multi_arr2_decode(&mut r) {
            let mut w = GronWriter::new();
            multi_arr2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr2 gron: write error"); failed += 1; }
        } else { println!("FAIL MultiArr2 gron: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_multi_arr3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = multi_arr3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            multi_arr3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr3 mp: write error"); failed += 1; }
        } else { println!("FAIL MultiArr3 mp: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr3_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr3 json: write error"); failed += 1; }
            } else { println!("FAIL MultiArr3 json: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr3 json: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr3_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL MultiArr3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = multi_arr3_decode(&mut r) {
            let mut w = GronWriter::new();
            multi_arr3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr3 gron: write error"); failed += 1; }
        } else { println!("FAIL MultiArr3 gron: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_multi_arr4(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr4.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = multi_arr4_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            multi_arr4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr4.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr4 mp: write error"); failed += 1; }
        } else { println!("FAIL MultiArr4 mp: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr4 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr4.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr4_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr4.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr4 json: write error"); failed += 1; }
            } else { println!("FAIL MultiArr4 json: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr4 json: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr4 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr4.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr4_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr4.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr4 unformatted: write error"); failed += 1; }
            } else { println!("FAIL MultiArr4 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr4 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr4 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr4.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = multi_arr4_decode(&mut r) {
            let mut w = GronWriter::new();
            multi_arr4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr4.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr4 gron: write error"); failed += 1; }
        } else { println!("FAIL MultiArr4 gron: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr4 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_multi_arr5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr5.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = multi_arr5_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            multi_arr5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr5.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr5 mp: write error"); failed += 1; }
        } else { println!("FAIL MultiArr5 mp: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr5 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr5.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr5_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr5.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr5 json: write error"); failed += 1; }
            } else { println!("FAIL MultiArr5 json: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr5 json: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr5 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr5.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = multi_arr5_decode(&mut r) {
                let mut w = JsonWriter::new();
                multi_arr5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr5.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL MultiArr5 unformatted: write error"); failed += 1; }
            } else { println!("FAIL MultiArr5 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL MultiArr5 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL MultiArr5 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("MultiArr5.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = multi_arr5_decode(&mut r) {
            let mut w = GronWriter::new();
            multi_arr5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("MultiArr5.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL MultiArr5 gron: write error"); failed += 1; }
        } else { println!("FAIL MultiArr5 gron: decode error"); failed += 1; }
    } else { println!("FAIL MultiArr5 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo1 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo1 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo1_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo1 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo1 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo1 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo1_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo1_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo1 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo1 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo2 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo2 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo2_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo2 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo2 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo2 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo2_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo2_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo2 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo2 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo3 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo3 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo3 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo3 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo3 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo3_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo3 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo3 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo4(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo4.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo4_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo4.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo4 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo4 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo4 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo4.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo4_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo4.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo4 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo4 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo4 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo4 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo4.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo4_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo4.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo4 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo4 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo4 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo4 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo4.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo4_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo4.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo4 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo4 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo4 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo5.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo5_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo5.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo5 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo5 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo5 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo5.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo5_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo5.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo5 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo5 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo5 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo5 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo5.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo5_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo5.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo5 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo5 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo5 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo5 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo5.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo5_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo5.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo5 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo5 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo5 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo6(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo6.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo6_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo6_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo6.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo6 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo6 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo6 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo6.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo6_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo6_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo6.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo6 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo6 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo6 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo6 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo6.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo6_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo6_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo6.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo6 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo6 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo6 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo6 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo6.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo6_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo6_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo6.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo6 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo6 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo6 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo7(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo7.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo7_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo7_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo7.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo7 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo7 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo7 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo7.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo7_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo7_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo7.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo7 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo7 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo7 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo7 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo7.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo7_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo7_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo7.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo7 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo7 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo7 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo7 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo7.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo7_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo7_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo7.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo7 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo7 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo7 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo8(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo8.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo8_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo8.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo8 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo8 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo8 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo8.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo8.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo8 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo8 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo8 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo8 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo8.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo8.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo8 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo8 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo8 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo8 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo8.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo8_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo8.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo8 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo8 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo8 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo9(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo9.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo9_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo9_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo9.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo9 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo9 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo9 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo9.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo9_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo9_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo9.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo9 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo9 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo9 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo9 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo9.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo9_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo9_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo9.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo9 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo9 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo9 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo9 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo9.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo9_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo9_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo9.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo9 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo9 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo9 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_combo10(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo10.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_combo10_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_combo10_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo10.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo10 mp: write error"); failed += 1; }
        } else { println!("FAIL OptCombo10 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo10 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo10.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo10_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo10_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo10.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo10 json: write error"); failed += 1; }
            } else { println!("FAIL OptCombo10 json: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo10 json: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo10 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo10.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_combo10_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_combo10_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo10.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptCombo10 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptCombo10 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptCombo10 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptCombo10 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptCombo10.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_combo10_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_combo10_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptCombo10.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptCombo10 gron: write error"); failed += 1; }
        } else { println!("FAIL OptCombo10 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptCombo10 gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_arr_string(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_int32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_boolean(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_float64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_bytes(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_int64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_arr_uint64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_multi_arr1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_multi_arr2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_multi_arr3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_multi_arr4(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_multi_arr5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo4(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo6(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo7(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo8(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo9(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_combo10(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
