// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_opt_types::*;


fn test_model_opt_single_string(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleString.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_string_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleString.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleString mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleString mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleString mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleString.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleString.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleString json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleString json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleString json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleString json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleString.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleString.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleString unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleString unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleString unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleString unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleString.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_string_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleString.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleString gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleString gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleString gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_boolean(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBoolean.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_boolean_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBoolean.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleBoolean mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleBoolean mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleBoolean mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBoolean.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBoolean.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleBoolean json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleBoolean json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleBoolean json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleBoolean json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBoolean.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBoolean.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleBoolean unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleBoolean unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleBoolean unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleBoolean unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBoolean.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_boolean_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBoolean.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleBoolean gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleBoolean gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleBoolean gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_int8(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt8.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_int8_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_int8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt8.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt8 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt8 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt8 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt8.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt8.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt8 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt8 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt8 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt8 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt8.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt8.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt8 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt8 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt8 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt8 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt8.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_int8_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_int8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt8.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt8 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt8 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt8 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_int16(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt16.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_int16_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_int16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt16.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt16 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt16 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt16 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt16.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int16_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt16.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt16 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt16 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt16 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt16 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt16.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int16_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt16.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt16 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt16 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt16 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt16 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt16.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_int16_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_int16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt16.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt16 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt16 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt16 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_int32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_int32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt32 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt32 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt32 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt32 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt32 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_int32_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt32 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt32 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_int64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_int64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt64 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt64 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt64 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt64 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt64 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleInt64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleInt64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleInt64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleInt64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleInt64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_int64_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleInt64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleInt64 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleInt64 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleInt64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_uint8(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint8.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_uint8_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_uint8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint8.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint8 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint8 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint8 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint8.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint8.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint8 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint8 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint8 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint8 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint8.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint8_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint8.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint8 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint8 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint8 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint8 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint8.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_uint8_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_uint8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint8.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint8 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint8 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint8 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_uint16(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint16.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_uint16_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_uint16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint16.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint16 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint16 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint16 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint16.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint16_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint16.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint16 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint16 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint16 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint16 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint16.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint16_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint16.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint16 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint16 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint16 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint16 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint16.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_uint16_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_uint16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint16.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint16 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint16 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint16 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_uint32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_uint32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_uint32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint32 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint32 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint32 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint32 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint32 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_uint32_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_uint32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint32 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint32 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_uint64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_uint64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint64 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint64 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint64 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint64 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint64 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleUint64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleUint64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleUint64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleUint64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleUint64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_uint64_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleUint64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleUint64 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleUint64 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleUint64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_float32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_float32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_float32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleFloat32 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat32 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_float32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_float32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleFloat32 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleFloat32 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat32 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_float32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_float32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleFloat32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleFloat32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_float32_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_float32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleFloat32 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat32 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_float64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_float64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleFloat64 mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat64 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleFloat64 json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleFloat64 json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat64 json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleFloat64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleFloat64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleFloat64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_float64_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleFloat64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleFloat64 gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleFloat64 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleFloat64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_single_bytes(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBytes.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_single_bytes_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_single_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBytes.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleBytes mp: write error"); failed += 1; }
        } else { println!("FAIL OptSingleBytes mp: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleBytes mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBytes.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBytes.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleBytes json: write error"); failed += 1; }
            } else { println!("FAIL OptSingleBytes json: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleBytes json: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleBytes json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBytes.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_single_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_single_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBytes.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptSingleBytes unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptSingleBytes unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptSingleBytes unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptSingleBytes unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptSingleBytes.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_single_bytes_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_single_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptSingleBytes.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptSingleBytes gron: write error"); failed += 1; }
        } else { println!("FAIL OptSingleBytes gron: decode error"); failed += 1; }
    } else { println!("FAIL OptSingleBytes gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_opt_single_string(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_boolean(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_int8(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_int16(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_int32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_int64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_uint8(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_uint16(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_uint32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_uint64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_float32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_float64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_single_bytes(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
