// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_nested_types::*;


fn test_model_nested_simple(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestedSimple.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nested_simple_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nested_simple_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestedSimple.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestedSimple mp: write error"); failed += 1; }
        } else { println!("FAIL NestedSimple mp: decode error"); failed += 1; }
    } else { println!("FAIL NestedSimple mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestedSimple.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nested_simple_decode(&mut r) {
                let mut w = JsonWriter::new();
                nested_simple_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestedSimple.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestedSimple json: write error"); failed += 1; }
            } else { println!("FAIL NestedSimple json: decode error"); failed += 1; }
        } else { println!("FAIL NestedSimple json: reader error"); failed += 1; }
    } else { println!("FAIL NestedSimple json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestedSimple.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nested_simple_decode(&mut r) {
                let mut w = JsonWriter::new();
                nested_simple_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestedSimple.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestedSimple unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestedSimple unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestedSimple unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestedSimple unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestedSimple.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nested_simple_decode(&mut r) {
            let mut w = GronWriter::new();
            nested_simple_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestedSimple.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestedSimple gron: write error"); failed += 1; }
        } else { println!("FAIL NestedSimple gron: decode error"); failed += 1; }
    } else { println!("FAIL NestedSimple gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_nested_simple(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
