// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_nests_types::*;


fn test_model_nest_inner(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestInner.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_inner_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_inner_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestInner.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestInner mp: write error"); failed += 1; }
        } else { println!("FAIL NestInner mp: decode error"); failed += 1; }
    } else { println!("FAIL NestInner mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestInner.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_inner_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_inner_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestInner.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestInner json: write error"); failed += 1; }
            } else { println!("FAIL NestInner json: decode error"); failed += 1; }
        } else { println!("FAIL NestInner json: reader error"); failed += 1; }
    } else { println!("FAIL NestInner json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestInner.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_inner_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_inner_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestInner.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestInner unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestInner unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestInner unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestInner unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestInner.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_inner_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_inner_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestInner.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestInner gron: write error"); failed += 1; }
        } else { println!("FAIL NestInner gron: decode error"); failed += 1; }
    } else { println!("FAIL NestInner gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_coord(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestCoord.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_coord_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_coord_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestCoord.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestCoord mp: write error"); failed += 1; }
        } else { println!("FAIL NestCoord mp: decode error"); failed += 1; }
    } else { println!("FAIL NestCoord mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestCoord.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_coord_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_coord_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestCoord.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestCoord json: write error"); failed += 1; }
            } else { println!("FAIL NestCoord json: decode error"); failed += 1; }
        } else { println!("FAIL NestCoord json: reader error"); failed += 1; }
    } else { println!("FAIL NestCoord json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestCoord.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_coord_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_coord_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestCoord.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestCoord unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestCoord unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestCoord unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestCoord unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestCoord.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_coord_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_coord_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestCoord.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestCoord gron: write error"); failed += 1; }
        } else { println!("FAIL NestCoord gron: decode error"); failed += 1; }
    } else { println!("FAIL NestCoord gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_id_val(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestIdVal.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_id_val_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_id_val_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestIdVal.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestIdVal mp: write error"); failed += 1; }
        } else { println!("FAIL NestIdVal mp: decode error"); failed += 1; }
    } else { println!("FAIL NestIdVal mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestIdVal.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_id_val_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_id_val_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestIdVal.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestIdVal json: write error"); failed += 1; }
            } else { println!("FAIL NestIdVal json: decode error"); failed += 1; }
        } else { println!("FAIL NestIdVal json: reader error"); failed += 1; }
    } else { println!("FAIL NestIdVal json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestIdVal.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_id_val_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_id_val_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestIdVal.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestIdVal unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestIdVal unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestIdVal unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestIdVal unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestIdVal.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_id_val_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_id_val_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestIdVal.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestIdVal gron: write error"); failed += 1; }
        } else { println!("FAIL NestIdVal gron: decode error"); failed += 1; }
    } else { println!("FAIL NestIdVal gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_label(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestLabel.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_label_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_label_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestLabel.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestLabel mp: write error"); failed += 1; }
        } else { println!("FAIL NestLabel mp: decode error"); failed += 1; }
    } else { println!("FAIL NestLabel mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestLabel.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_label_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_label_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestLabel.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestLabel json: write error"); failed += 1; }
            } else { println!("FAIL NestLabel json: decode error"); failed += 1; }
        } else { println!("FAIL NestLabel json: reader error"); failed += 1; }
    } else { println!("FAIL NestLabel json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestLabel.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_label_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_label_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestLabel.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestLabel unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestLabel unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestLabel unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestLabel unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestLabel.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_label_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_label_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestLabel.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestLabel gron: write error"); failed += 1; }
        } else { println!("FAIL NestLabel gron: decode error"); failed += 1; }
    } else { println!("FAIL NestLabel gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_money(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestMoney.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_money_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_money_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestMoney.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestMoney mp: write error"); failed += 1; }
        } else { println!("FAIL NestMoney mp: decode error"); failed += 1; }
    } else { println!("FAIL NestMoney mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestMoney.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_money_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_money_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestMoney.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestMoney json: write error"); failed += 1; }
            } else { println!("FAIL NestMoney json: decode error"); failed += 1; }
        } else { println!("FAIL NestMoney json: reader error"); failed += 1; }
    } else { println!("FAIL NestMoney json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestMoney.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_money_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_money_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestMoney.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestMoney unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestMoney unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestMoney unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestMoney unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestMoney.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_money_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_money_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestMoney.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestMoney gron: write error"); failed += 1; }
        } else { println!("FAIL NestMoney gron: decode error"); failed += 1; }
    } else { println!("FAIL NestMoney gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_range32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestRange32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_range32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_range32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestRange32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestRange32 mp: write error"); failed += 1; }
        } else { println!("FAIL NestRange32 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestRange32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestRange32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_range32_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_range32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestRange32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestRange32 json: write error"); failed += 1; }
            } else { println!("FAIL NestRange32 json: decode error"); failed += 1; }
        } else { println!("FAIL NestRange32 json: reader error"); failed += 1; }
    } else { println!("FAIL NestRange32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestRange32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_range32_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_range32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestRange32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestRange32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestRange32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestRange32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestRange32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestRange32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_range32_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_range32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestRange32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestRange32 gron: write error"); failed += 1; }
        } else { println!("FAIL NestRange32 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestRange32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_addr(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestAddr.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_addr_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_addr_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestAddr.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestAddr mp: write error"); failed += 1; }
        } else { println!("FAIL NestAddr mp: decode error"); failed += 1; }
    } else { println!("FAIL NestAddr mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestAddr.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_addr_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_addr_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestAddr.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestAddr json: write error"); failed += 1; }
            } else { println!("FAIL NestAddr json: decode error"); failed += 1; }
        } else { println!("FAIL NestAddr json: reader error"); failed += 1; }
    } else { println!("FAIL NestAddr json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestAddr.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_addr_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_addr_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestAddr.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestAddr unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestAddr unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestAddr unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestAddr unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestAddr.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_addr_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_addr_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestAddr.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestAddr gron: write error"); failed += 1; }
        } else { println!("FAIL NestAddr gron: decode error"); failed += 1; }
    } else { println!("FAIL NestAddr gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_point3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestPoint3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_point3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_point3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestPoint3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestPoint3 mp: write error"); failed += 1; }
        } else { println!("FAIL NestPoint3 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestPoint3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestPoint3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_point3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_point3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestPoint3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestPoint3 json: write error"); failed += 1; }
            } else { println!("FAIL NestPoint3 json: decode error"); failed += 1; }
        } else { println!("FAIL NestPoint3 json: reader error"); failed += 1; }
    } else { println!("FAIL NestPoint3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestPoint3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_point3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_point3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestPoint3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestPoint3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestPoint3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestPoint3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestPoint3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestPoint3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_point3_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_point3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestPoint3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestPoint3 gron: write error"); failed += 1; }
        } else { println!("FAIL NestPoint3 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestPoint3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_inner(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestInner.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_inner_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_inner_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestInner.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestInner mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestInner mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestInner mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestInner.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_inner_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_inner_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestInner.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestInner json: write error"); failed += 1; }
            } else { println!("FAIL OptNestInner json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestInner json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestInner json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestInner.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_inner_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_inner_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestInner.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestInner unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestInner unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestInner unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestInner unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestInner.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_inner_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_inner_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestInner.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestInner gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestInner gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestInner gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_coord(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestCoord.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_coord_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_coord_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestCoord.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestCoord mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestCoord mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestCoord mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestCoord.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_coord_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_coord_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestCoord.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestCoord json: write error"); failed += 1; }
            } else { println!("FAIL OptNestCoord json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestCoord json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestCoord json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestCoord.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_coord_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_coord_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestCoord.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestCoord unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestCoord unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestCoord unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestCoord unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestCoord.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_coord_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_coord_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestCoord.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestCoord gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestCoord gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestCoord gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_id_val(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestIdVal.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_id_val_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_id_val_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestIdVal.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestIdVal mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestIdVal mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestIdVal mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestIdVal.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_id_val_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_id_val_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestIdVal.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestIdVal json: write error"); failed += 1; }
            } else { println!("FAIL OptNestIdVal json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestIdVal json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestIdVal json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestIdVal.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_id_val_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_id_val_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestIdVal.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestIdVal unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestIdVal unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestIdVal unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestIdVal unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestIdVal.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_id_val_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_id_val_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestIdVal.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestIdVal gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestIdVal gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestIdVal gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_label(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestLabel.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_label_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_label_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestLabel.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestLabel mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestLabel mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestLabel mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestLabel.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_label_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_label_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestLabel.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestLabel json: write error"); failed += 1; }
            } else { println!("FAIL OptNestLabel json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestLabel json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestLabel json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestLabel.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_label_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_label_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestLabel.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestLabel unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestLabel unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestLabel unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestLabel unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestLabel.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_label_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_label_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestLabel.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestLabel gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestLabel gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestLabel gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_money(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestMoney.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_money_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_money_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestMoney.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestMoney mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestMoney mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestMoney mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestMoney.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_money_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_money_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestMoney.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestMoney json: write error"); failed += 1; }
            } else { println!("FAIL OptNestMoney json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestMoney json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestMoney json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestMoney.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_money_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_money_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestMoney.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestMoney unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestMoney unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestMoney unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestMoney unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestMoney.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_money_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_money_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestMoney.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestMoney gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestMoney gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestMoney gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_range32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestRange32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_range32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_range32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestRange32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestRange32 mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestRange32 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestRange32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestRange32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_range32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_range32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestRange32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestRange32 json: write error"); failed += 1; }
            } else { println!("FAIL OptNestRange32 json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestRange32 json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestRange32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestRange32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_range32_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_range32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestRange32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestRange32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestRange32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestRange32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestRange32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestRange32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_range32_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_range32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestRange32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestRange32 gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestRange32 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestRange32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_addr(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestAddr.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_addr_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_addr_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestAddr.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestAddr mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestAddr mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestAddr mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestAddr.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_addr_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_addr_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestAddr.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestAddr json: write error"); failed += 1; }
            } else { println!("FAIL OptNestAddr json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestAddr json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestAddr json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestAddr.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_addr_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_addr_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestAddr.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestAddr unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestAddr unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestAddr unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestAddr unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestAddr.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_addr_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_addr_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestAddr.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestAddr gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestAddr gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestAddr gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_nest_point3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestPoint3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_nest_point3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_nest_point3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestPoint3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestPoint3 mp: write error"); failed += 1; }
        } else { println!("FAIL OptNestPoint3 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptNestPoint3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestPoint3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_point3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_point3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestPoint3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestPoint3 json: write error"); failed += 1; }
            } else { println!("FAIL OptNestPoint3 json: decode error"); failed += 1; }
        } else { println!("FAIL OptNestPoint3 json: reader error"); failed += 1; }
    } else { println!("FAIL OptNestPoint3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestPoint3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_nest_point3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_nest_point3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestPoint3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptNestPoint3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptNestPoint3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptNestPoint3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptNestPoint3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptNestPoint3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_nest_point3_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_nest_point3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptNestPoint3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptNestPoint3 gron: write error"); failed += 1; }
        } else { println!("FAIL OptNestPoint3 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptNestPoint3 gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_nest_inner(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_coord(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_id_val(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_label(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_money(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_range32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_addr(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_point3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_inner(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_coord(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_id_val(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_label(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_money(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_range32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_addr(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_nest_point3(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
