// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_edge_types::*;


fn test_model_edge_empty(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeEmpty.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_empty_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_empty_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeEmpty.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeEmpty mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeEmpty mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeEmpty mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeEmpty.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_empty_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_empty_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeEmpty.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeEmpty json: write error"); failed += 1; }
            } else { println!("FAIL EdgeEmpty json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeEmpty json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeEmpty json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeEmpty.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_empty_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_empty_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeEmpty.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeEmpty unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeEmpty unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeEmpty unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeEmpty unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeEmpty.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_empty_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_empty_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeEmpty.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeEmpty gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeEmpty gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeEmpty gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_one_opt(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeOneOpt.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_one_opt_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_one_opt_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeOneOpt.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeOneOpt mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeOneOpt mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeOneOpt mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeOneOpt.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_one_opt_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_one_opt_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeOneOpt.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeOneOpt json: write error"); failed += 1; }
            } else { println!("FAIL EdgeOneOpt json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeOneOpt json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeOneOpt json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeOneOpt.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_one_opt_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_one_opt_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeOneOpt.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeOneOpt unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeOneOpt unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeOneOpt unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeOneOpt unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeOneOpt.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_one_opt_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_one_opt_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeOneOpt.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeOneOpt gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeOneOpt gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeOneOpt gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_big_nums(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBigNums.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_big_nums_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_big_nums_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBigNums.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBigNums mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeBigNums mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBigNums mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBigNums.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_big_nums_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_big_nums_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBigNums.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBigNums json: write error"); failed += 1; }
            } else { println!("FAIL EdgeBigNums json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBigNums json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBigNums json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBigNums.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_big_nums_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_big_nums_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBigNums.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBigNums unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeBigNums unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBigNums unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBigNums unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBigNums.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_big_nums_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_big_nums_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBigNums.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBigNums gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeBigNums gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBigNums gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_zero_vals(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeZeroVals.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_zero_vals_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_zero_vals_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeZeroVals.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeZeroVals mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeZeroVals mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeZeroVals mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeZeroVals.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_zero_vals_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_zero_vals_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeZeroVals.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeZeroVals json: write error"); failed += 1; }
            } else { println!("FAIL EdgeZeroVals json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeZeroVals json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeZeroVals json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeZeroVals.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_zero_vals_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_zero_vals_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeZeroVals.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeZeroVals unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeZeroVals unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeZeroVals unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeZeroVals unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeZeroVals.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_zero_vals_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_zero_vals_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeZeroVals.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeZeroVals gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeZeroVals gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeZeroVals gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_nullable(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullable.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_nullable_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_nullable_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullable.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNullable mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeNullable mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNullable mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullable.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_nullable_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_nullable_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullable.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNullable json: write error"); failed += 1; }
            } else { println!("FAIL EdgeNullable json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNullable json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNullable json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullable.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_nullable_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_nullable_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullable.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNullable unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeNullable unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNullable unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNullable unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullable.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_nullable_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_nullable_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullable.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNullable gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeNullable gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNullable gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_neg_zero(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNegZero.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_neg_zero_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_neg_zero_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNegZero.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNegZero mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeNegZero mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNegZero mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNegZero.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_neg_zero_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_neg_zero_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNegZero.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNegZero json: write error"); failed += 1; }
            } else { println!("FAIL EdgeNegZero json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNegZero json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNegZero json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNegZero.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_neg_zero_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_neg_zero_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNegZero.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNegZero unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeNegZero unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNegZero unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNegZero unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNegZero.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_neg_zero_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_neg_zero_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNegZero.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNegZero gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeNegZero gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNegZero gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_null_byte(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullByte.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_null_byte_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_null_byte_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullByte.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNullByte mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeNullByte mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNullByte mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullByte.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_null_byte_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_null_byte_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullByte.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNullByte json: write error"); failed += 1; }
            } else { println!("FAIL EdgeNullByte json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNullByte json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNullByte json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullByte.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_null_byte_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_null_byte_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullByte.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeNullByte unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeNullByte unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeNullByte unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeNullByte unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeNullByte.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_null_byte_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_null_byte_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeNullByte.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeNullByte gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeNullByte gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeNullByte gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_boundary(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBoundary.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_boundary_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_boundary_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBoundary.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBoundary mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeBoundary mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBoundary mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBoundary.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_boundary_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_boundary_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBoundary.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBoundary json: write error"); failed += 1; }
            } else { println!("FAIL EdgeBoundary json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBoundary json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBoundary json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBoundary.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_boundary_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_boundary_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBoundary.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBoundary unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeBoundary unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBoundary unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBoundary unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBoundary.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_boundary_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_boundary_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBoundary.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBoundary gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeBoundary gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBoundary gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_str_len(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeStrLen.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_str_len_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_str_len_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeStrLen.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeStrLen mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeStrLen mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeStrLen mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeStrLen.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_str_len_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_str_len_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeStrLen.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeStrLen json: write error"); failed += 1; }
            } else { println!("FAIL EdgeStrLen json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeStrLen json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeStrLen json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeStrLen.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_str_len_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_str_len_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeStrLen.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeStrLen unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeStrLen unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeStrLen unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeStrLen unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeStrLen.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_str_len_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_str_len_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeStrLen.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeStrLen gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeStrLen gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeStrLen gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_bytes_len(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBytesLen.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_bytes_len_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_bytes_len_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBytesLen.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBytesLen mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeBytesLen mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBytesLen mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBytesLen.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_bytes_len_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_bytes_len_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBytesLen.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBytesLen json: write error"); failed += 1; }
            } else { println!("FAIL EdgeBytesLen json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBytesLen json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBytesLen json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBytesLen.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_bytes_len_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_bytes_len_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBytesLen.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeBytesLen unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeBytesLen unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeBytesLen unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeBytesLen unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeBytesLen.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_bytes_len_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_bytes_len_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeBytesLen.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeBytesLen gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeBytesLen gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeBytesLen gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_arr_empty(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrEmpty.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_arr_empty_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_arr_empty_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrEmpty.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeArrEmpty mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeArrEmpty mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeArrEmpty mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrEmpty.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_arr_empty_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_arr_empty_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrEmpty.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeArrEmpty json: write error"); failed += 1; }
            } else { println!("FAIL EdgeArrEmpty json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeArrEmpty json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeArrEmpty json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrEmpty.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_arr_empty_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_arr_empty_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrEmpty.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeArrEmpty unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeArrEmpty unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeArrEmpty unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeArrEmpty unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrEmpty.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_arr_empty_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_arr_empty_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrEmpty.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeArrEmpty gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeArrEmpty gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeArrEmpty gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_edge_arr_boundary(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrBoundary.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = edge_arr_boundary_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            edge_arr_boundary_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrBoundary.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeArrBoundary mp: write error"); failed += 1; }
        } else { println!("FAIL EdgeArrBoundary mp: decode error"); failed += 1; }
    } else { println!("FAIL EdgeArrBoundary mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrBoundary.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_arr_boundary_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_arr_boundary_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrBoundary.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeArrBoundary json: write error"); failed += 1; }
            } else { println!("FAIL EdgeArrBoundary json: decode error"); failed += 1; }
        } else { println!("FAIL EdgeArrBoundary json: reader error"); failed += 1; }
    } else { println!("FAIL EdgeArrBoundary json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrBoundary.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = edge_arr_boundary_decode(&mut r) {
                let mut w = JsonWriter::new();
                edge_arr_boundary_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrBoundary.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL EdgeArrBoundary unformatted: write error"); failed += 1; }
            } else { println!("FAIL EdgeArrBoundary unformatted: decode error"); failed += 1; }
        } else { println!("FAIL EdgeArrBoundary unformatted: reader error"); failed += 1; }
    } else { println!("FAIL EdgeArrBoundary unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("EdgeArrBoundary.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = edge_arr_boundary_decode(&mut r) {
            let mut w = GronWriter::new();
            edge_arr_boundary_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("EdgeArrBoundary.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL EdgeArrBoundary gron: write error"); failed += 1; }
        } else { println!("FAIL EdgeArrBoundary gron: decode error"); failed += 1; }
    } else { println!("FAIL EdgeArrBoundary gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_edge_empty(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_one_opt(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_big_nums(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_zero_vals(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_nullable(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_neg_zero(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_null_byte(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_boundary(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_str_len(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_bytes_len(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_arr_empty(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_edge_arr_boundary(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
