// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_wide_types::*;


fn test_model_wide20(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide20.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = wide20_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            wide20_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide20.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide20 mp: write error"); failed += 1; }
        } else { println!("FAIL Wide20 mp: decode error"); failed += 1; }
    } else { println!("FAIL Wide20 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide20.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide20_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide20_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide20.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide20 json: write error"); failed += 1; }
            } else { println!("FAIL Wide20 json: decode error"); failed += 1; }
        } else { println!("FAIL Wide20 json: reader error"); failed += 1; }
    } else { println!("FAIL Wide20 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide20.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide20_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide20_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide20.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide20 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Wide20 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Wide20 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Wide20 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide20.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = wide20_decode(&mut r) {
            let mut w = GronWriter::new();
            wide20_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide20.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide20 gron: write error"); failed += 1; }
        } else { println!("FAIL Wide20 gron: decode error"); failed += 1; }
    } else { println!("FAIL Wide20 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_wide25(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide25.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = wide25_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            wide25_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide25.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide25 mp: write error"); failed += 1; }
        } else { println!("FAIL Wide25 mp: decode error"); failed += 1; }
    } else { println!("FAIL Wide25 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide25.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide25_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide25_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide25.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide25 json: write error"); failed += 1; }
            } else { println!("FAIL Wide25 json: decode error"); failed += 1; }
        } else { println!("FAIL Wide25 json: reader error"); failed += 1; }
    } else { println!("FAIL Wide25 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide25.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide25_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide25_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide25.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide25 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Wide25 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Wide25 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Wide25 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide25.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = wide25_decode(&mut r) {
            let mut w = GronWriter::new();
            wide25_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide25.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide25 gron: write error"); failed += 1; }
        } else { println!("FAIL Wide25 gron: decode error"); failed += 1; }
    } else { println!("FAIL Wide25 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_wide30(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide30.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = wide30_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            wide30_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide30.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide30 mp: write error"); failed += 1; }
        } else { println!("FAIL Wide30 mp: decode error"); failed += 1; }
    } else { println!("FAIL Wide30 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide30.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide30_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide30_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide30.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide30 json: write error"); failed += 1; }
            } else { println!("FAIL Wide30 json: decode error"); failed += 1; }
        } else { println!("FAIL Wide30 json: reader error"); failed += 1; }
    } else { println!("FAIL Wide30 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide30.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide30_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide30_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide30.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide30 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Wide30 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Wide30 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Wide30 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide30.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = wide30_decode(&mut r) {
            let mut w = GronWriter::new();
            wide30_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide30.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide30 gron: write error"); failed += 1; }
        } else { println!("FAIL Wide30 gron: decode error"); failed += 1; }
    } else { println!("FAIL Wide30 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_wide35(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide35.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = wide35_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            wide35_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide35.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide35 mp: write error"); failed += 1; }
        } else { println!("FAIL Wide35 mp: decode error"); failed += 1; }
    } else { println!("FAIL Wide35 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide35.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide35_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide35_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide35.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide35 json: write error"); failed += 1; }
            } else { println!("FAIL Wide35 json: decode error"); failed += 1; }
        } else { println!("FAIL Wide35 json: reader error"); failed += 1; }
    } else { println!("FAIL Wide35 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide35.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide35_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide35_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide35.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide35 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Wide35 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Wide35 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Wide35 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide35.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = wide35_decode(&mut r) {
            let mut w = GronWriter::new();
            wide35_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide35.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide35 gron: write error"); failed += 1; }
        } else { println!("FAIL Wide35 gron: decode error"); failed += 1; }
    } else { println!("FAIL Wide35 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_wide40(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide40.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = wide40_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            wide40_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide40.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide40 mp: write error"); failed += 1; }
        } else { println!("FAIL Wide40 mp: decode error"); failed += 1; }
    } else { println!("FAIL Wide40 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide40.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide40_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide40_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide40.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide40 json: write error"); failed += 1; }
            } else { println!("FAIL Wide40 json: decode error"); failed += 1; }
        } else { println!("FAIL Wide40 json: reader error"); failed += 1; }
    } else { println!("FAIL Wide40 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide40.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = wide40_decode(&mut r) {
                let mut w = JsonWriter::new();
                wide40_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide40.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL Wide40 unformatted: write error"); failed += 1; }
            } else { println!("FAIL Wide40 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL Wide40 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL Wide40 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("Wide40.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = wide40_decode(&mut r) {
            let mut w = GronWriter::new();
            wide40_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("Wide40.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL Wide40 gron: write error"); failed += 1; }
        } else { println!("FAIL Wide40 gron: decode error"); failed += 1; }
    } else { println!("FAIL Wide40 gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_wide20(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_wide25(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_wide30(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_wide35(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_wide40(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
