// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_nested_deep_types::*;


fn test_model_deep_model(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepModel.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_model_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_model_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepModel.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepModel mp: write error"); failed += 1; }
        } else { println!("FAIL DeepModel mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepModel mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepModel.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_model_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_model_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepModel.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepModel json: write error"); failed += 1; }
            } else { println!("FAIL DeepModel json: decode error"); failed += 1; }
        } else { println!("FAIL DeepModel json: reader error"); failed += 1; }
    } else { println!("FAIL DeepModel json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepModel.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_model_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_model_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepModel.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepModel unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepModel unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepModel unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepModel unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepModel.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_model_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_model_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepModel.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepModel gron: write error"); failed += 1; }
        } else { println!("FAIL DeepModel gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepModel gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_deep_model(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
