// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_extra_types::*;


fn test_model_opt_arr1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_arr1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_arr1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr1 mp: write error"); failed += 1; }
        } else { println!("FAIL OptArr1 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptArr1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr1_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr1 json: write error"); failed += 1; }
            } else { println!("FAIL OptArr1 json: decode error"); failed += 1; }
        } else { println!("FAIL OptArr1 json: reader error"); failed += 1; }
    } else { println!("FAIL OptArr1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr1_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptArr1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptArr1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptArr1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_arr1_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_arr1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr1 gron: write error"); failed += 1; }
        } else { println!("FAIL OptArr1 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptArr1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_arr2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_arr2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_arr2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr2 mp: write error"); failed += 1; }
        } else { println!("FAIL OptArr2 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptArr2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr2_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr2 json: write error"); failed += 1; }
            } else { println!("FAIL OptArr2 json: decode error"); failed += 1; }
        } else { println!("FAIL OptArr2 json: reader error"); failed += 1; }
    } else { println!("FAIL OptArr2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr2_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptArr2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptArr2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptArr2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_arr2_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_arr2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr2 gron: write error"); failed += 1; }
        } else { println!("FAIL OptArr2 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptArr2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_arr3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_arr3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_arr3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr3 mp: write error"); failed += 1; }
        } else { println!("FAIL OptArr3 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptArr3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr3 json: write error"); failed += 1; }
            } else { println!("FAIL OptArr3 json: decode error"); failed += 1; }
        } else { println!("FAIL OptArr3 json: reader error"); failed += 1; }
    } else { println!("FAIL OptArr3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr3_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptArr3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptArr3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptArr3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_arr3_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_arr3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr3 gron: write error"); failed += 1; }
        } else { println!("FAIL OptArr3 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptArr3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_arr4(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr4.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_arr4_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_arr4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr4.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr4 mp: write error"); failed += 1; }
        } else { println!("FAIL OptArr4 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptArr4 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr4.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr4_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr4.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr4 json: write error"); failed += 1; }
            } else { println!("FAIL OptArr4 json: decode error"); failed += 1; }
        } else { println!("FAIL OptArr4 json: reader error"); failed += 1; }
    } else { println!("FAIL OptArr4 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr4.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr4_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr4.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr4 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptArr4 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptArr4 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptArr4 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr4.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_arr4_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_arr4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr4.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr4 gron: write error"); failed += 1; }
        } else { println!("FAIL OptArr4 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptArr4 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_opt_arr5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr5.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = opt_arr5_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            opt_arr5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr5.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr5 mp: write error"); failed += 1; }
        } else { println!("FAIL OptArr5 mp: decode error"); failed += 1; }
    } else { println!("FAIL OptArr5 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr5.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr5_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr5.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr5 json: write error"); failed += 1; }
            } else { println!("FAIL OptArr5 json: decode error"); failed += 1; }
        } else { println!("FAIL OptArr5 json: reader error"); failed += 1; }
    } else { println!("FAIL OptArr5 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr5.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = opt_arr5_decode(&mut r) {
                let mut w = JsonWriter::new();
                opt_arr5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr5.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL OptArr5 unformatted: write error"); failed += 1; }
            } else { println!("FAIL OptArr5 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL OptArr5 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL OptArr5 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("OptArr5.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = opt_arr5_decode(&mut r) {
            let mut w = GronWriter::new();
            opt_arr5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("OptArr5.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL OptArr5 gron: write error"); failed += 1; }
        } else { println!("FAIL OptArr5 gron: decode error"); failed += 1; }
    } else { println!("FAIL OptArr5 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt1 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOpt1 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt1_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt1 json: write error"); failed += 1; }
            } else { println!("FAIL NestOpt1 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt1 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt1_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOpt1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt1_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt1 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOpt1 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt2 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOpt2 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt2_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt2 json: write error"); failed += 1; }
            } else { println!("FAIL NestOpt2 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt2 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt2_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOpt2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt2_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt2 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOpt2 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt3 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOpt3 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt3 json: write error"); failed += 1; }
            } else { println!("FAIL NestOpt3 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt3 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOpt3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt3_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt3 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOpt3 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt4(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt4.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt4_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt4.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt4 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOpt4 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt4 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt4.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt4_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt4.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt4 json: write error"); failed += 1; }
            } else { println!("FAIL NestOpt4 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt4 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt4 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt4.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt4_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt4.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt4 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOpt4 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt4 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt4 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt4.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt4_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt4.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt4 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOpt4 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt4 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt5.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt5_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt5.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt5 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOpt5 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt5 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt5.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt5_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt5.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt5 json: write error"); failed += 1; }
            } else { println!("FAIL NestOpt5 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt5 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt5 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt5.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt5_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt5.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOpt5 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOpt5 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOpt5 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOpt5 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOpt5.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt5_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOpt5.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOpt5 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOpt5 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOpt5 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt_inner1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt_inner1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt_inner1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner1 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner1 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner1_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner1 json: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner1 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner1 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner1_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt_inner1_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt_inner1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner1 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner1 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt_inner2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt_inner2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt_inner2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner2 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner2 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner2_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner2 json: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner2 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner2 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner2_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt_inner2_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt_inner2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner2 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner2 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_nest_opt_inner3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = nest_opt_inner3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            nest_opt_inner3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner3 mp: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner3 mp: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner3 json: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner3 json: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner3 json: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = nest_opt_inner3_decode(&mut r) {
                let mut w = JsonWriter::new();
                nest_opt_inner3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL NestOptInner3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL NestOptInner3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL NestOptInner3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL NestOptInner3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("NestOptInner3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = nest_opt_inner3_decode(&mut r) {
            let mut w = GronWriter::new();
            nest_opt_inner3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("NestOptInner3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL NestOptInner3 gron: write error"); failed += 1; }
        } else { println!("FAIL NestOptInner3 gron: decode error"); failed += 1; }
    } else { println!("FAIL NestOptInner3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest1(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest1.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest1_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest1.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest1 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest1 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest1 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest1.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest1_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest1.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest1 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest1 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest1 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest1 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest1.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest1_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest1_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest1.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest1 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest1 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest1 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest1 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest1.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest1_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest1_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest1.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest1 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest1 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest1 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest2(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest2.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest2_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest2.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest2 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest2 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest2 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest2.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest2_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest2.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest2 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest2 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest2 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest2 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest2.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest2_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest2_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest2.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest2 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest2 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest2 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest2 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest2.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest2_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest2_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest2.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest2 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest2 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest2 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest3(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest3.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest3_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest3.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest3 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest3 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest3 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest3.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest3_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest3.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest3 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest3 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest3 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest3 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest3.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest3_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest3_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest3.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest3 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest3 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest3 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest3 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest3.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest3_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest3_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest3.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest3 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest3 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest3 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest4(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest4.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest4_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest4.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest4 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest4 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest4 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest4.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest4_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest4.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest4 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest4 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest4 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest4 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest4.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest4_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest4_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest4.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest4 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest4 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest4 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest4 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest4.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest4_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest4_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest4.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest4 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest4 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest4 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest5.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest5_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest5.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest5 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest5 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest5 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest5.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest5_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest5.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest5 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest5 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest5 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest5 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest5.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest5_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest5_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest5.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest5 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest5 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest5 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest5 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest5.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest5_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest5_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest5.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest5 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest5 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest5 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest6(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest6.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest6_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest6_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest6.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest6 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest6 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest6 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest6.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest6_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest6_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest6.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest6 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest6 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest6 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest6 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest6.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest6_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest6_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest6.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest6 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest6 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest6 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest6 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest6.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest6_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest6_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest6.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest6 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest6 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest6 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_deep_nest7(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest7.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = deep_nest7_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            deep_nest7_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest7.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest7 mp: write error"); failed += 1; }
        } else { println!("FAIL DeepNest7 mp: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest7 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest7.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest7_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest7_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest7.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest7 json: write error"); failed += 1; }
            } else { println!("FAIL DeepNest7 json: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest7 json: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest7 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest7.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = deep_nest7_decode(&mut r) {
                let mut w = JsonWriter::new();
                deep_nest7_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest7.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL DeepNest7 unformatted: write error"); failed += 1; }
            } else { println!("FAIL DeepNest7 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL DeepNest7 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL DeepNest7 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("DeepNest7.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = deep_nest7_decode(&mut r) {
            let mut w = GronWriter::new();
            deep_nest7_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("DeepNest7.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL DeepNest7 gron: write error"); failed += 1; }
        } else { println!("FAIL DeepNest7 gron: decode error"); failed += 1; }
    } else { println!("FAIL DeepNest7 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_timestamp_entry(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("TimestampEntry.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = timestamp_entry_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            timestamp_entry_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("TimestampEntry.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL TimestampEntry mp: write error"); failed += 1; }
        } else { println!("FAIL TimestampEntry mp: decode error"); failed += 1; }
    } else { println!("FAIL TimestampEntry mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("TimestampEntry.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = timestamp_entry_decode(&mut r) {
                let mut w = JsonWriter::new();
                timestamp_entry_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("TimestampEntry.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL TimestampEntry json: write error"); failed += 1; }
            } else { println!("FAIL TimestampEntry json: decode error"); failed += 1; }
        } else { println!("FAIL TimestampEntry json: reader error"); failed += 1; }
    } else { println!("FAIL TimestampEntry json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("TimestampEntry.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = timestamp_entry_decode(&mut r) {
                let mut w = JsonWriter::new();
                timestamp_entry_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("TimestampEntry.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL TimestampEntry unformatted: write error"); failed += 1; }
            } else { println!("FAIL TimestampEntry unformatted: decode error"); failed += 1; }
        } else { println!("FAIL TimestampEntry unformatted: reader error"); failed += 1; }
    } else { println!("FAIL TimestampEntry unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("TimestampEntry.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = timestamp_entry_decode(&mut r) {
            let mut w = GronWriter::new();
            timestamp_entry_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("TimestampEntry.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL TimestampEntry gron: write error"); failed += 1; }
        } else { println!("FAIL TimestampEntry gron: decode error"); failed += 1; }
    } else { println!("FAIL TimestampEntry gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_config_entry(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ConfigEntry.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = config_entry_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            config_entry_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ConfigEntry.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ConfigEntry mp: write error"); failed += 1; }
        } else { println!("FAIL ConfigEntry mp: decode error"); failed += 1; }
    } else { println!("FAIL ConfigEntry mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ConfigEntry.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = config_entry_decode(&mut r) {
                let mut w = JsonWriter::new();
                config_entry_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ConfigEntry.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ConfigEntry json: write error"); failed += 1; }
            } else { println!("FAIL ConfigEntry json: decode error"); failed += 1; }
        } else { println!("FAIL ConfigEntry json: reader error"); failed += 1; }
    } else { println!("FAIL ConfigEntry json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ConfigEntry.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = config_entry_decode(&mut r) {
                let mut w = JsonWriter::new();
                config_entry_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("ConfigEntry.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL ConfigEntry unformatted: write error"); failed += 1; }
            } else { println!("FAIL ConfigEntry unformatted: decode error"); failed += 1; }
        } else { println!("FAIL ConfigEntry unformatted: reader error"); failed += 1; }
    } else { println!("FAIL ConfigEntry unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("ConfigEntry.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = config_entry_decode(&mut r) {
            let mut w = GronWriter::new();
            config_entry_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("ConfigEntry.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL ConfigEntry gron: write error"); failed += 1; }
        } else { println!("FAIL ConfigEntry gron: decode error"); failed += 1; }
    } else { println!("FAIL ConfigEntry gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_opt_arr1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_arr2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_arr3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_arr4(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_opt_arr5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt4(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt_inner1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt_inner2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_nest_opt_inner3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest1(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest2(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest3(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest4(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest6(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_deep_nest7(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_timestamp_entry(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_config_entry(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
