// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_scalars_types::*;


fn test_model_single_string(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleString.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_string_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleString.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleString mp: write error"); failed += 1; }
        } else { println!("FAIL SingleString mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleString mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleString.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleString.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleString json: write error"); failed += 1; }
            } else { println!("FAIL SingleString json: decode error"); failed += 1; }
        } else { println!("FAIL SingleString json: reader error"); failed += 1; }
    } else { println!("FAIL SingleString json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleString.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_string_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_string_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleString.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleString unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleString unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleString unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleString unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleString.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_string_decode(&mut r) {
            let mut w = GronWriter::new();
            single_string_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleString.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleString gron: write error"); failed += 1; }
        } else { println!("FAIL SingleString gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleString gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_boolean(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBoolean.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_boolean_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBoolean.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleBoolean mp: write error"); failed += 1; }
        } else { println!("FAIL SingleBoolean mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleBoolean mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBoolean.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBoolean.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleBoolean json: write error"); failed += 1; }
            } else { println!("FAIL SingleBoolean json: decode error"); failed += 1; }
        } else { println!("FAIL SingleBoolean json: reader error"); failed += 1; }
    } else { println!("FAIL SingleBoolean json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBoolean.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_boolean_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_boolean_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBoolean.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleBoolean unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleBoolean unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleBoolean unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleBoolean unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBoolean.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_boolean_decode(&mut r) {
            let mut w = GronWriter::new();
            single_boolean_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBoolean.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleBoolean gron: write error"); failed += 1; }
        } else { println!("FAIL SingleBoolean gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleBoolean gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_int8(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt8.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_int8_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_int8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt8.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt8 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleInt8 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt8 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt8.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int8_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt8.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt8 json: write error"); failed += 1; }
            } else { println!("FAIL SingleInt8 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt8 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt8 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt8.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int8_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt8.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt8 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleInt8 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt8 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt8 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt8.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_int8_decode(&mut r) {
            let mut w = GronWriter::new();
            single_int8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt8.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt8 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleInt8 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt8 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_int16(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt16.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_int16_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_int16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt16.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt16 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleInt16 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt16 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt16.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int16_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt16.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt16 json: write error"); failed += 1; }
            } else { println!("FAIL SingleInt16 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt16 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt16 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt16.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int16_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt16.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt16 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleInt16 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt16 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt16 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt16.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_int16_decode(&mut r) {
            let mut w = GronWriter::new();
            single_int16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt16.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt16 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleInt16 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt16 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_int32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_int32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt32 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleInt32 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt32 json: write error"); failed += 1; }
            } else { println!("FAIL SingleInt32 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt32 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleInt32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_int32_decode(&mut r) {
            let mut w = GronWriter::new();
            single_int32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt32 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleInt32 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_int64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_int64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt64 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleInt64 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt64 json: write error"); failed += 1; }
            } else { println!("FAIL SingleInt64 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt64 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_int64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_int64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleInt64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleInt64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleInt64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleInt64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleInt64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_int64_decode(&mut r) {
            let mut w = GronWriter::new();
            single_int64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleInt64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleInt64 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleInt64 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleInt64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_uint8(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint8.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_uint8_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_uint8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint8.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint8 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleUint8 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint8 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint8.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint8_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint8.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint8 json: write error"); failed += 1; }
            } else { println!("FAIL SingleUint8 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint8 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint8 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint8.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint8_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint8_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint8.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint8 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleUint8 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint8 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint8 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint8.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_uint8_decode(&mut r) {
            let mut w = GronWriter::new();
            single_uint8_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint8.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint8 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleUint8 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint8 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_uint16(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint16.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_uint16_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_uint16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint16.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint16 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleUint16 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint16 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint16.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint16_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint16.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint16 json: write error"); failed += 1; }
            } else { println!("FAIL SingleUint16 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint16 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint16 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint16.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint16_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint16_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint16.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint16 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleUint16 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint16 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint16 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint16.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_uint16_decode(&mut r) {
            let mut w = GronWriter::new();
            single_uint16_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint16.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint16 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleUint16 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint16 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_uint32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_uint32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_uint32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint32 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleUint32 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint32 json: write error"); failed += 1; }
            } else { println!("FAIL SingleUint32 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint32 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleUint32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_uint32_decode(&mut r) {
            let mut w = GronWriter::new();
            single_uint32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint32 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleUint32 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_uint64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_uint64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint64 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleUint64 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint64 json: write error"); failed += 1; }
            } else { println!("FAIL SingleUint64 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint64 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_uint64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_uint64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleUint64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleUint64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleUint64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleUint64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleUint64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_uint64_decode(&mut r) {
            let mut w = GronWriter::new();
            single_uint64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleUint64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleUint64 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleUint64 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleUint64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_float32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat32.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_float32_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_float32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat32.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleFloat32 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleFloat32 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleFloat32 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat32.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_float32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_float32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat32.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleFloat32 json: write error"); failed += 1; }
            } else { println!("FAIL SingleFloat32 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleFloat32 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleFloat32 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat32.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_float32_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_float32_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat32.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleFloat32 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleFloat32 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleFloat32 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleFloat32 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat32.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_float32_decode(&mut r) {
            let mut w = GronWriter::new();
            single_float32_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat32.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleFloat32 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleFloat32 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleFloat32 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_float64(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat64.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_float64_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat64.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleFloat64 mp: write error"); failed += 1; }
        } else { println!("FAIL SingleFloat64 mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleFloat64 mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat64.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat64.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleFloat64 json: write error"); failed += 1; }
            } else { println!("FAIL SingleFloat64 json: decode error"); failed += 1; }
        } else { println!("FAIL SingleFloat64 json: reader error"); failed += 1; }
    } else { println!("FAIL SingleFloat64 json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat64.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_float64_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_float64_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat64.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleFloat64 unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleFloat64 unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleFloat64 unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleFloat64 unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleFloat64.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_float64_decode(&mut r) {
            let mut w = GronWriter::new();
            single_float64_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleFloat64.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleFloat64 gron: write error"); failed += 1; }
        } else { println!("FAIL SingleFloat64 gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleFloat64 gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_single_bytes(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBytes.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = single_bytes_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            single_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBytes.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleBytes mp: write error"); failed += 1; }
        } else { println!("FAIL SingleBytes mp: decode error"); failed += 1; }
    } else { println!("FAIL SingleBytes mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBytes.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBytes.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleBytes json: write error"); failed += 1; }
            } else { println!("FAIL SingleBytes json: decode error"); failed += 1; }
        } else { println!("FAIL SingleBytes json: reader error"); failed += 1; }
    } else { println!("FAIL SingleBytes json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBytes.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = single_bytes_decode(&mut r) {
                let mut w = JsonWriter::new();
                single_bytes_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBytes.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL SingleBytes unformatted: write error"); failed += 1; }
            } else { println!("FAIL SingleBytes unformatted: decode error"); failed += 1; }
        } else { println!("FAIL SingleBytes unformatted: reader error"); failed += 1; }
    } else { println!("FAIL SingleBytes unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("SingleBytes.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = single_bytes_decode(&mut r) {
            let mut w = GronWriter::new();
            single_bytes_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("SingleBytes.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL SingleBytes gron: write error"); failed += 1; }
        } else { println!("FAIL SingleBytes gron: decode error"); failed += 1; }
    } else { println!("FAIL SingleBytes gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_single_string(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_boolean(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_int8(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_int16(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_int32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_int64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_uint8(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_uint16(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_uint32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_uint64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_float32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_float64(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_single_bytes(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
