// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, SpecReader, SpecWriter};


fn test_scalar_int8_min(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int8_min.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int8_min.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int8_min mp: write error"); failed += 1; }
        } else { println!("FAIL int8_min mp: read error"); failed += 1; }
    } else { println!("FAIL int8_min mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int8_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int8_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int8_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int8_max mp: write error"); failed += 1; }
        } else { println!("FAIL int8_max mp: read error"); failed += 1; }
    } else { println!("FAIL int8_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int16_min(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int16_min.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int16_min.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int16_min mp: write error"); failed += 1; }
        } else { println!("FAIL int16_min mp: read error"); failed += 1; }
    } else { println!("FAIL int16_min mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int16_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int16_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int16_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int16_max mp: write error"); failed += 1; }
        } else { println!("FAIL int16_max mp: read error"); failed += 1; }
    } else { println!("FAIL int16_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int32_min(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int32_min.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int32_min.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int32_min mp: write error"); failed += 1; }
        } else { println!("FAIL int32_min mp: read error"); failed += 1; }
    } else { println!("FAIL int32_min mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int32_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int32_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int32() {
            let mut w = MsgPackWriter::new();
            w.write_int32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int32_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int32_max mp: write error"); failed += 1; }
        } else { println!("FAIL int32_max mp: read error"); failed += 1; }
    } else { println!("FAIL int32_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int64_min(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int64_min.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int64() {
            let mut w = MsgPackWriter::new();
            w.write_int64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int64_min.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int64_min mp: write error"); failed += 1; }
        } else { println!("FAIL int64_min mp: read error"); failed += 1; }
    } else { println!("FAIL int64_min mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_int64_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/int64_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_int64() {
            let mut w = MsgPackWriter::new();
            w.write_int64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/int64_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL int64_max mp: write error"); failed += 1; }
        } else { println!("FAIL int64_max mp: read error"); failed += 1; }
    } else { println!("FAIL int64_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_uint8_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/uint8_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_uint32() {
            let mut w = MsgPackWriter::new();
            w.write_uint32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/uint8_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL uint8_max mp: write error"); failed += 1; }
        } else { println!("FAIL uint8_max mp: read error"); failed += 1; }
    } else { println!("FAIL uint8_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_uint16_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/uint16_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_uint32() {
            let mut w = MsgPackWriter::new();
            w.write_uint32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/uint16_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL uint16_max mp: write error"); failed += 1; }
        } else { println!("FAIL uint16_max mp: read error"); failed += 1; }
    } else { println!("FAIL uint16_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_uint32_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/uint32_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_uint32() {
            let mut w = MsgPackWriter::new();
            w.write_uint32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/uint32_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL uint32_max mp: write error"); failed += 1; }
        } else { println!("FAIL uint32_max mp: read error"); failed += 1; }
    } else { println!("FAIL uint32_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_uint64_max(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/uint64_max.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_uint64() {
            let mut w = MsgPackWriter::new();
            w.write_uint64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/uint64_max.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL uint64_max mp: write error"); failed += 1; }
        } else { println!("FAIL uint64_max mp: read error"); failed += 1; }
    } else { println!("FAIL uint64_max mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float32_1_5(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float32_1.5.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float32() {
            let mut w = MsgPackWriter::new();
            w.write_float32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float32_1.5.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float32_1.5 mp: write error"); failed += 1; }
        } else { println!("FAIL float32_1.5 mp: read error"); failed += 1; }
    } else { println!("FAIL float32_1.5 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float32_neg_zero(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float32_neg_zero.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float32() {
            let mut w = MsgPackWriter::new();
            w.write_float32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float32_neg_zero.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float32_neg_zero mp: write error"); failed += 1; }
        } else { println!("FAIL float32_neg_zero mp: read error"); failed += 1; }
    } else { println!("FAIL float32_neg_zero mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float32_inf(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float32_inf.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float32() {
            let mut w = MsgPackWriter::new();
            w.write_float32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float32_inf.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float32_inf mp: write error"); failed += 1; }
        } else { println!("FAIL float32_inf mp: read error"); failed += 1; }
    } else { println!("FAIL float32_inf mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float32_neg_inf(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float32_neg_inf.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float32() {
            let mut w = MsgPackWriter::new();
            w.write_float32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float32_neg_inf.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float32_neg_inf mp: write error"); failed += 1; }
        } else { println!("FAIL float32_neg_inf mp: read error"); failed += 1; }
    } else { println!("FAIL float32_neg_inf mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float32_nan(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float32_nan.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float32() {
            let mut w = MsgPackWriter::new();
            w.write_float32(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float32_nan.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float32_nan mp: write error"); failed += 1; }
        } else { println!("FAIL float32_nan mp: read error"); failed += 1; }
    } else { println!("FAIL float32_nan mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float64_pi(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float64_pi.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float64() {
            let mut w = MsgPackWriter::new();
            w.write_float64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float64_pi.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float64_pi mp: write error"); failed += 1; }
        } else { println!("FAIL float64_pi mp: read error"); failed += 1; }
    } else { println!("FAIL float64_pi mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float64_neg_zero(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float64_neg_zero.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float64() {
            let mut w = MsgPackWriter::new();
            w.write_float64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float64_neg_zero.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float64_neg_zero mp: write error"); failed += 1; }
        } else { println!("FAIL float64_neg_zero mp: read error"); failed += 1; }
    } else { println!("FAIL float64_neg_zero mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float64_inf(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float64_inf.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float64() {
            let mut w = MsgPackWriter::new();
            w.write_float64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float64_inf.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float64_inf mp: write error"); failed += 1; }
        } else { println!("FAIL float64_inf mp: read error"); failed += 1; }
    } else { println!("FAIL float64_inf mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float64_neg_inf(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float64_neg_inf.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float64() {
            let mut w = MsgPackWriter::new();
            w.write_float64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float64_neg_inf.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float64_neg_inf mp: write error"); failed += 1; }
        } else { println!("FAIL float64_neg_inf mp: read error"); failed += 1; }
    } else { println!("FAIL float64_neg_inf mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_float64_nan(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/float64_nan.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_float64() {
            let mut w = MsgPackWriter::new();
            w.write_float64(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/float64_nan.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL float64_nan mp: write error"); failed += 1; }
        } else { println!("FAIL float64_nan mp: read error"); failed += 1; }
    } else { println!("FAIL float64_nan mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_empty(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_empty.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_empty.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_empty mp: write error"); failed += 1; }
        } else { println!("FAIL str_empty mp: read error"); failed += 1; }
    } else { println!("FAIL str_empty mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_ascii(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_ascii.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_ascii.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_ascii mp: write error"); failed += 1; }
        } else { println!("FAIL str_ascii mp: read error"); failed += 1; }
    } else { println!("FAIL str_ascii mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_null_byte(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_null_byte.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_null_byte.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_null_byte mp: write error"); failed += 1; }
        } else { println!("FAIL str_null_byte mp: read error"); failed += 1; }
    } else { println!("FAIL str_null_byte mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_escape(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_escape.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_escape.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_escape mp: write error"); failed += 1; }
        } else { println!("FAIL str_escape mp: read error"); failed += 1; }
    } else { println!("FAIL str_escape mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_unicode(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_unicode.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_unicode.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_unicode mp: write error"); failed += 1; }
        } else { println!("FAIL str_unicode mp: read error"); failed += 1; }
    } else { println!("FAIL str_unicode mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_31(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_31.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_31.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_31 mp: write error"); failed += 1; }
        } else { println!("FAIL str_31 mp: read error"); failed += 1; }
    } else { println!("FAIL str_31 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_32.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_32.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_32 mp: write error"); failed += 1; }
        } else { println!("FAIL str_32 mp: read error"); failed += 1; }
    } else { println!("FAIL str_32 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_255(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_255.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_255.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_255 mp: write error"); failed += 1; }
        } else { println!("FAIL str_255 mp: read error"); failed += 1; }
    } else { println!("FAIL str_255 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_str_256(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/str_256.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_string() {
            let mut w = MsgPackWriter::new();
            w.write_string(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/str_256.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL str_256 mp: write error"); failed += 1; }
        } else { println!("FAIL str_256 mp: read error"); failed += 1; }
    } else { println!("FAIL str_256 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_empty(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_empty.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_empty.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_empty mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_empty mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_empty mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_small(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_small.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_small.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_small mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_small mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_small mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_31(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_31.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_31.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_31 mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_31 mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_31 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_32(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_32.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_32.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_32 mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_32 mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_32 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_255(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_255.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_255.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_255 mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_255 mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_255 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_256(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_256.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_256.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_256 mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_256 mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_256 mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_zeros(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_zeros.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_zeros.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_zeros mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_zeros mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_zeros mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bytes_ff(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bytes_ff.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bytes() {
            let mut w = MsgPackWriter::new();
            w.write_bytes(&val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bytes_ff.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bytes_ff mp: write error"); failed += 1; }
        } else { println!("FAIL bytes_ff mp: read error"); failed += 1; }
    } else { println!("FAIL bytes_ff mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bool_true(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bool_true.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bool() {
            let mut w = MsgPackWriter::new();
            w.write_bool(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bool_true.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bool_true mp: write error"); failed += 1; }
        } else { println!("FAIL bool_true mp: read error"); failed += 1; }
    } else { println!("FAIL bool_true mp: file not found"); failed += 1; }
    (passed, failed)
}

fn test_scalar_bool_false(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("scalars/bool_false.mp")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(val) = r.read_bool() {
            let mut w = MsgPackWriter::new();
            w.write_bool(val);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("scalars/bool_false.mp"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL bool_false mp: write error"); failed += 1; }
        } else { println!("FAIL bool_false mp: read error"); failed += 1; }
    } else { println!("FAIL bool_false mp: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_scalar_int8_min(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int8_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int16_min(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int16_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int32_min(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int32_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int64_min(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_int64_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_uint8_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_uint16_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_uint32_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_uint64_max(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float32_1_5(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float32_neg_zero(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float32_inf(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float32_neg_inf(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float32_nan(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float64_pi(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float64_neg_zero(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float64_inf(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float64_neg_inf(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_float64_nan(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_empty(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_ascii(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_null_byte(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_escape(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_unicode(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_31(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_255(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_str_256(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_empty(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_small(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_31(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_32(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_255(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_256(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_zeros(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bytes_ff(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bool_true(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_scalar_bool_false(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
