// Generated by generate_emit_runner.mjs. DO NOT EDIT.
use std::fs;
use std::path::Path;
use specodec::{MsgPackReader, MsgPackWriter, JsonReader, JsonWriter, GronReader, GronWriter, SpecReader, SpecWriter};
use crate::generated::all_types_recursive_types::*;


fn test_model_rec_list(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecList.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = rec_list_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            rec_list_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecList.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecList mp: write error"); failed += 1; }
        } else { println!("FAIL RecList mp: decode error"); failed += 1; }
    } else { println!("FAIL RecList mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecList.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_list_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_list_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecList.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecList json: write error"); failed += 1; }
            } else { println!("FAIL RecList json: decode error"); failed += 1; }
        } else { println!("FAIL RecList json: reader error"); failed += 1; }
    } else { println!("FAIL RecList json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecList.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_list_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_list_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecList.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecList unformatted: write error"); failed += 1; }
            } else { println!("FAIL RecList unformatted: decode error"); failed += 1; }
        } else { println!("FAIL RecList unformatted: reader error"); failed += 1; }
    } else { println!("FAIL RecList unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecList.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = rec_list_decode(&mut r) {
            let mut w = GronWriter::new();
            rec_list_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecList.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecList gron: write error"); failed += 1; }
        } else { println!("FAIL RecList gron: decode error"); failed += 1; }
    } else { println!("FAIL RecList gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_rec_tree(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecTree.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = rec_tree_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            rec_tree_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecTree.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecTree mp: write error"); failed += 1; }
        } else { println!("FAIL RecTree mp: decode error"); failed += 1; }
    } else { println!("FAIL RecTree mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecTree.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_tree_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_tree_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecTree.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecTree json: write error"); failed += 1; }
            } else { println!("FAIL RecTree json: decode error"); failed += 1; }
        } else { println!("FAIL RecTree json: reader error"); failed += 1; }
    } else { println!("FAIL RecTree json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecTree.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_tree_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_tree_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecTree.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecTree unformatted: write error"); failed += 1; }
            } else { println!("FAIL RecTree unformatted: decode error"); failed += 1; }
        } else { println!("FAIL RecTree unformatted: reader error"); failed += 1; }
    } else { println!("FAIL RecTree unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecTree.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = rec_tree_decode(&mut r) {
            let mut w = GronWriter::new();
            rec_tree_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecTree.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecTree gron: write error"); failed += 1; }
        } else { println!("FAIL RecTree gron: decode error"); failed += 1; }
    } else { println!("FAIL RecTree gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_rec_chain(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecChain.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = rec_chain_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            rec_chain_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecChain.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecChain mp: write error"); failed += 1; }
        } else { println!("FAIL RecChain mp: decode error"); failed += 1; }
    } else { println!("FAIL RecChain mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecChain.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_chain_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_chain_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecChain.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecChain json: write error"); failed += 1; }
            } else { println!("FAIL RecChain json: decode error"); failed += 1; }
        } else { println!("FAIL RecChain json: reader error"); failed += 1; }
    } else { println!("FAIL RecChain json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecChain.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_chain_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_chain_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecChain.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecChain unformatted: write error"); failed += 1; }
            } else { println!("FAIL RecChain unformatted: decode error"); failed += 1; }
        } else { println!("FAIL RecChain unformatted: reader error"); failed += 1; }
    } else { println!("FAIL RecChain unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecChain.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = rec_chain_decode(&mut r) {
            let mut w = GronWriter::new();
            rec_chain_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecChain.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecChain gron: write error"); failed += 1; }
        } else { println!("FAIL RecChain gron: decode error"); failed += 1; }
    } else { println!("FAIL RecChain gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_rec_wrap(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWrap.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = rec_wrap_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            rec_wrap_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWrap.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecWrap mp: write error"); failed += 1; }
        } else { println!("FAIL RecWrap mp: decode error"); failed += 1; }
    } else { println!("FAIL RecWrap mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWrap.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_wrap_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_wrap_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWrap.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecWrap json: write error"); failed += 1; }
            } else { println!("FAIL RecWrap json: decode error"); failed += 1; }
        } else { println!("FAIL RecWrap json: reader error"); failed += 1; }
    } else { println!("FAIL RecWrap json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWrap.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_wrap_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_wrap_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWrap.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecWrap unformatted: write error"); failed += 1; }
            } else { println!("FAIL RecWrap unformatted: decode error"); failed += 1; }
        } else { println!("FAIL RecWrap unformatted: reader error"); failed += 1; }
    } else { println!("FAIL RecWrap unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWrap.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = rec_wrap_decode(&mut r) {
            let mut w = GronWriter::new();
            rec_wrap_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWrap.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecWrap gron: write error"); failed += 1; }
        } else { println!("FAIL RecWrap gron: decode error"); failed += 1; }
    } else { println!("FAIL RecWrap gron: file not found"); failed += 1; }
    (passed, failed)
}

fn test_model_rec_wide(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    // msgpack
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWide.msgpack")) {
        let mut r = MsgPackReader::new(&b);
        if let Ok(obj) = rec_wide_decode(&mut r) {
            let mut w = MsgPackWriter::new();
            rec_wide_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWide.msgpack"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecWide mp: write error"); failed += 1; }
        } else { println!("FAIL RecWide mp: decode error"); failed += 1; }
    } else { println!("FAIL RecWide mp: file not found"); failed += 1; }
    // json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWide.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_wide_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_wide_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWide.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecWide json: write error"); failed += 1; }
            } else { println!("FAIL RecWide json: decode error"); failed += 1; }
        } else { println!("FAIL RecWide json: reader error"); failed += 1; }
    } else { println!("FAIL RecWide json: file not found"); failed += 1; }
    // unformatted json
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWide.unformatted.json")) {
        if let Ok(mut r) = JsonReader::new(&b) {
            if let Ok(obj) = rec_wide_decode(&mut r) {
                let mut w = JsonWriter::new();
                rec_wide_write(&obj, &mut w);
                if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWide.unformatted.json"), w.to_bytes()) {
                    passed += 1;
                } else { println!("FAIL RecWide unformatted: write error"); failed += 1; }
            } else { println!("FAIL RecWide unformatted: decode error"); failed += 1; }
        } else { println!("FAIL RecWide unformatted: reader error"); failed += 1; }
    } else { println!("FAIL RecWide unformatted: file not found"); failed += 1; }
    // gron
    if let Ok(b) = fs::read(Path::new(&vec_dir).join("RecWide.gron")) {
        let mut r = GronReader::new(&b);
        if let Ok(obj) = rec_wide_decode(&mut r) {
            let mut w = GronWriter::new();
            rec_wide_write(&obj, &mut w);
            if let Ok(_) = fs::write(Path::new(&out_dir).join("RecWide.gron"), w.to_bytes()) {
                passed += 1;
            } else { println!("FAIL RecWide gron: write error"); failed += 1; }
        } else { println!("FAIL RecWide gron: decode error"); failed += 1; }
    } else { println!("FAIL RecWide gron: file not found"); failed += 1; }
    (passed, failed)
}


pub fn run(vec_dir: &str, out_dir: &str) -> (u32, u32) {
    let mut passed = 0u32;
    let mut failed = 0u32;
    let (p, f) = test_model_rec_list(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_rec_tree(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_rec_chain(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_rec_wrap(vec_dir, out_dir); passed += p; failed += f;
    let (p, f) = test_model_rec_wide(vec_dir, out_dir); passed += p; failed += f;

    (passed, failed)
}
