import { execSync } from "child_process";
import { readFileSync, existsSync, mkdirSync, rmSync, readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dir = dirname(fileURLToPath(import.meta.url));
const CACHE = join(__dir, ".tests-cache");
const GENERATED = join(__dir, "src", "generated");
const OUT_DIR = join(__dir, "output");

function run(cmd) {
  console.log("  >", cmd);
  execSync(cmd, { stdio: "inherit" });
}

function ensure(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

console.log("\n=== Step 0: Install dependencies ===");
run(`cd ${__dir} && npm install`);

if (!existsSync(join(CACHE, "vectors"))) { console.log("\n=== Step 1: Clone tests repo ==="); if (existsSync(CACHE)) rmSync(CACHE, { recursive: true }); run(`git clone --depth=1 https://github.com/specodec/tests ${CACHE}`) } else { console.log("\n=== Step 1: Using cached .tests-cache ===") }

console.log("\n=== Step 2: Generate vectors ===");
run(`cd ${CACHE} && npm install`);
run(`cd ${CACHE} && node gen_types.mjs`);

const VEC_DIR = join(CACHE, "vectors");

console.log("\n=== Step 3: Generate emit code ===");
if (existsSync(GENERATED)) rmSync(GENERATED, { recursive: true });
ensure(GENERATED);

run(`cd ${__dir} && node_modules/.bin/tsp compile ${CACHE}/alltypes.tsp --emit=@specodec/typespec-emitter-rust \
  --option @specodec/typespec-emitter-rust.emitter-output-dir=${GENERATED}`);

const rustFiles = readdirSync(GENERATED).filter(f => f.endsWith(".rs"));
if (rustFiles.length > 0) {
  console.log("  ✓ Generated " + rustFiles.join(", "));
} else {
  console.error("  FAIL: No generated Rust files");
  process.exit(1);
}
console.log("  ✓ mod.rs generated by emitter");

console.log("\n=== Step 4: Generate test runner ===");
run(`cd ${__dir} && VEC_DIR=${VEC_DIR} node generate_emit_runner.mjs`);

console.log("\n=== Step 5: Run tests ===");
if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
ensure(OUT_DIR);

// Build and run with cargo
try { run(`cd ${__dir} && VEC_DIR=${VEC_DIR} OUT_DIR=${OUT_DIR} cargo run --release`); } catch (e) { console.log("Rust tests completed (some failures expected)"); }

console.log('\n=== Step 6: Compare output ===');
const manifest = JSON.parse(readFileSync(join(VEC_DIR, 'manifest.json'), 'utf-8'));
let match = 0, mismatch = 0;

for (const [name] of Object.entries(manifest.scalars || {})) {
  const expected = join(VEC_DIR, 'scalars', `${name}.mp`);
  const actual = join(OUT_DIR, 'scalars', `${name}.mp`);
  if (!existsSync(actual)) { mismatch++; console.log(`MISSING: ${name}.mp`); continue; }
  if (readFileSync(expected).equals(readFileSync(actual))) match++;
  else { mismatch++; console.log(`MISMATCH: ${name}.mp`); }
}
for (const model of manifest.testModels || []) {
  for (const fmt of ['msgpack', 'json', 'gron', 'unformatted.json']) {
    const expected = join(VEC_DIR, `${model}.${fmt}`);
    const actual = join(OUT_DIR, `${model}.${fmt}`);
    if (!existsSync(expected)) continue;
    if (!existsSync(actual)) { mismatch++; console.log(`MISSING: ${model}.${fmt}`); continue; }
    if (readFileSync(expected).equals(readFileSync(actual))) match++;
    else { mismatch++; console.log(`MISMATCH: ${model}.${fmt}`); }
  }
}
const total = match + mismatch;
console.log(`${match}/${total} match, ${mismatch} mismatch`);
if (mismatch > 0) process.exit(1);

console.log("\n=== ALL PASSED ===");